#!/bin/bash
#
# Title:      Shell In A Box (siab)
# Author(s):  timekills/sspreitzer
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
# Docker:     Docker image is available at: https://github.com/sspreitzer/shellinabox
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'siab'
        intport: '4200'
        extport: '4200'
        image: 'sspreitzer/shellinabox:latest'

    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # EXTRA FUNCTIONS REQUIRED BY THE ROLE #####################################

    # LABELS #### KEEPS BOTTOM CLEAN ###########################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting default Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/home/:rw'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/mnt:/mnt'

    - name: 'Setting default ENV'
      set_fact:
        pg_env:
          SIAB_ADDUSER: "true"
          SIAB_USER: "siab"
          SIAB_GROUP: "guest"
          SIAB_PASSWORD: "!plexguide!"
          SIAB_SHELL: "/bin/bash"
          SIAB_HOME: "/home/siab"
          SIAB_SUDO: "true"
          SIAB_SSL: "false"


    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '4200:4200/tcp'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        expose:
          - 4200
        state: started
        labels: '{{pg_labels}}'
