#!/bin/bash
#
# Title:      UbuntuGUI
# Author(s):  timekills
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
# Docker:     Docker image is available at: https://github.com/fcwu/docker-ubuntu-vnc-desktop
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ubvnc'
        intport: '80'
        extport: '6080'
        intport2: '5900'
        extport2: '5900'
        image: 'dorowu/ubuntu-desktop-lxde-vnc:bionic-lxqt'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    - name: 'Including plugins'
      include_tasks: '/opt/communityapps/apps/_plugins.yml'

    - name: 'Including folders'
      include_tasks: '/opt/communityapps/apps/_downloaders.yml'

    - name: 'Ini Check'
      stat:
        path: /opt/appdata/{{pgrole}}/core.conf
      register: inicheck
      
     # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting default Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/home/apps:rw'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/mnt:/mnt'
          - '/dev/shm:/dev/shm'
          - '/dev/snd:/dev/snd:rw'
          - '/dev/dri:/dev/dri:rw'

    - name: 'Setting default ENV'
      set_fact:
        pg_env:
          USER_ID: 1000
          GROUP_ID: 1000
          DISPLAY_WIDTH: 1600
          DISPLAY_HEIGHT: 900
          USER: "apps"
          VNC_PASSWORD: "test!"
          PASSWORD: "!test!"
          ALSADEV: "hw:2,0"
#          SECURE_CONNECTION: 1


    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        expose:
          - 5900
          - 6080
        state: started
        labels: '{{pg_labels}}'
